export const workerColumn = [
    {
        field: 'name',
        headerName: '이름',
        flex: 1.5,
        headerAlign: "center",
        align: "center",
        editable: false,
    },
    {
        field: 'age',
        headerName: '나이',
        flex: 1,
        editable: false,
        headerAlign: "center",
        align: "center",
    },
    {
        field: 'contact',
        headerName: '연락처',
        flex: 1,
        editable: false,
        headerAlign: "center",
        align: "center",
    },
    {
        field: 'nationality',
        headerName: '국적',
        flex: 1,
        editable: false,
        headerAlign: "center",
        align: "center",
    },
    {
        field: 'visaType',
        headerName: '비자',
        flex: 1,
        editable: false,
        headerAlign: "center",
        align: "center",
    },
]