export const historyColumn = [
    {
        field: 'name',
        headerName: '이름',
        flex: 1.5,
        headerAlign: "center",
        align: "center",
        editable: false,
    },
    {
        field: 'age',
        headerName: '나이',
        flex: 1,
        editable: false,
        headerAlign: "center",
        align: "center",
    },
    {
        field: 'startDate',
        headerName: '근무 시작일',
        flex: 1,
        editable: false,
        headerAlign: "center",
        align: "center",
    },
    {
        field: 'endDate',
        headerName: '근무 종료일',
        flex: 1,
        editable: false,
        headerAlign: "center",
        align: "center",
    },
    {
        field: 'visaType',
        headerName: '비자',
        flex: 1,
        editable: false,
        headerAlign: "center",
        align: "center",
    },
]